version: '3'

services:
  # Servicio de frontend
  frontend:
    build: ./Frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:5000
    networks:
      - app-network

  # Servicio de backend (API)
  backend:
    build: ./Backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/loginapp
      - JWT_SECRET=misecreto123
      - PORT=5000
    networks:
      - app-network

  # Servicio de base de datos
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local